# Generated by Django 4.1.3 on 2022-12-08 23:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.IntegerField(choices=[(1, 'Web'), (2, 'Infrastructure'), (3, 'Android application'), (4, 'iOS application'), (5, 'Code'), (6, 'IoT'), (7, 'Other')], default=1)),
                ('notes', tinymce.models.HTMLField(default='TBC')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('risk', models.IntegerField(choices=[(1, 'Informative'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=1)),
                ('cvss', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Ready'), (3, 'Finished')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Other')], default=1)),
                ('description', tinymce.models.HTMLField(default='TBC')),
                ('impact', tinymce.models.HTMLField(default='TBC')),
                ('recomendation', tinymce.models.HTMLField(default='TBC')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('risk', models.IntegerField(choices=[(1, 'Informative'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=1)),
                ('cvss', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Ready'), (3, 'Finished')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Other')], default=1)),
                ('description', tinymce.models.HTMLField(default='TBC')),
                ('impact', tinymce.models.HTMLField(default='TBC')),
                ('recomendation', tinymce.models.HTMLField(default='TBC')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Planning'), (2, 'On course'), (3, 'Paused'), (4, 'Finished')], default=1)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(auto_now_add=True)),
                ('notes', tinymce.models.HTMLField(blank=True, default='TBC', null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='AssetVulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.asset')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vulnerability')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vulnerabilities',
            field=models.ManyToManyField(to='app.vulnerability'),
        ),
    ]
