# Generated by Django 3.0.5 on 2021-09-10 16:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('notes', tinymce.models.HTMLField(default='TBC')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('risk', models.IntegerField(choices=[(1, 'Informative'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')])),
                ('cvss', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Ready'), (3, 'Finished')])),
                ('description', tinymce.models.HTMLField(default='TBC')),
                ('impact', tinymce.models.HTMLField(default='TBC')),
                ('recomendation', tinymce.models.HTMLField(default='TBC')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('risk', models.IntegerField(choices=[(1, 'Informative'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=1)),
                ('cvss', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Ready'), (3, 'Finished')], default=1)),
                ('description', tinymce.models.HTMLField(default='TBC')),
                ('impact', tinymce.models.HTMLField(default='TBC')),
                ('recomendation', tinymce.models.HTMLField(default='TBC')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Planning'), (2, 'On course'), (3, 'Paused'), (4, 'Finished')], default=1)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(auto_now_add=True)),
                ('notes', tinymce.models.HTMLField(default='TBC')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='AssetVulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Asset')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Vulnerability')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vulnerabilities',
            field=models.ManyToManyField(through='app.AssetVulnerability', to='app.Vulnerability'),
        ),
    ]
