# Generated by Django 3.0.5 on 2021-09-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.IntegerField(choices=[(1, 'Web'), (2, 'Infrastructure'), (3, 'Android application'), (4, 'iOS application'), (5, 'Code'), (6, 'IoT'), (7, 'Other')], default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.IntegerField(choices=[(1, 'Other')], default=1),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='type',
            field=models.IntegerField(choices=[(1, 'Other')], default=1),
        ),
    ]
