# Generated by Django 3.0.5 on 2021-09-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210911_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
        migrations.AlterField(
            model_name='template',
            name='risk',
            field=models.IntegerField(choices=[(1, 'Informative'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=1),
        ),
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Ready'), (3, 'Finished')], default=1),
        ),
    ]
